services:
  db:
    image: postgres:12.20-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./conf/init-db:/docker-entrypoint-initdb.d
